FROM python:3.10-slim

WORKDIR /app

# Cài đặt pandoc và các gói cần thiết (ví dụ: curl nếu muốn dùng pypandoc.download_pandoc sau này)
RUN apt-get update && \
    apt-get install -y pandoc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Cài đặt Python dependencies
RUN pip install --no-cache-dir fastapi \
    uvicorn \
    python-dotenv \
    langchain_core==0.3.65 \
    langchain==0.3.25 \
    pydantic \
    pypandoc==1.15 \
    google-api-python-client==2.172.0 \
    google-auth-httplib2==0.2.0 \
    google-auth-oauthlib==1.2.2 

# Copy source code
COPY src/ ./src/
# Copy source code
COPY env/ ./env/

EXPOSE 9099

ENV PYTHONPATH=/app

CMD ["python3", "-m", "uvicorn", "src.MCP.server:app", "--host", "0.0.0.0", "--port", "9099"]
