FROM python:3.10-slim
WORKDIR /app

# Copy code
COPY requirements.txt requirements.txt

# Cài đặt thư viện cần thiết
RUN pip install --no-cache-dir  -r requirements.txt

RUN pip install --no-cache-dir  python-dotenv fastembed

COPY . .
# Embed rồi tự dừng container
CMD ["python", "emmbed_data.py"]
